### ISSUE TITLE
Fix atmospheric pressure offset

### ISSUE THREAD

**Issue by dheideman** [bluerobotics/BlueRobotics_KellerLD_Library#1]
https://github.com/bluerobotics/BlueRobotics_KellerLD_Library/blob/6bc8119cd98c457d0bd0255d4c1c060a79256237/KellerLD.cpp#L60

Should be 1.01325, not 1.0325.

**Comment by abaldur** [comment]
I have used the library with the PAA version (Absolute. Zero at vacuum). As shown in "Communication Protocol 4 LD ... 9 LD" page 9, the pressure is computed from this equation:

p[bar] = ( P – 16384 ) x ( Pmax – Pmin ) / 32768 + Pmin

Hence, the P_bar should be:
`P_bar = (float(P)-16384)*(P_max-P_min)/32768 + P_min + P_min;`

**Comment by ES-Alexander** [comment]
@dheideman's comment was seemingly fixed in [this commit](https://github.com/bluerobotics/BlueRobotics_KellerLD_Library/commit/1a741ceb5054dc14326c8df637f83d7d96506d38) (1 Sep 2017), but it seems there's a bigger issue whereby the pressure offset in the code is for P-Mode PR (1atm), whereas the Bar100 sensor uses P-Mode PA (sealed), which measures "Zero at 1,0 bar abs" (as per [Communication Protocol](http://www.keller-druck2.ch/swupdate/InstallerD-LineAddressManager/manual/Communication_Protocol_4LD-9LD_en.pdf#page=12) section 5.1, page 12). This was raised in [this forum thread](https://discuss.bluerobotics.com/t/bar100-keller-pa-sealed-gauge/10046).

This and @abaldur's comment also raise the issue that the offset should be based off the P-mode (which is read in [here in the code](https://github.com/bluerobotics/BlueRobotics_KellerLD_Library/blob/master/KellerLD.cpp#L31) and then seemingly not used) - otherwise the only supported sensor type is PR, which we're not actually using.

>Hence, the P_bar should be:
`P_bar = (float(P)-16384)*(P_max-P_min)/32768 + P_min + P_min;`

This^ isn't quite correct, as `P_min` is based on the operating range, whereas the final offset should be based purely on the P-mode (one P-mode can apply to multiple operating ranges), so I believe it should instead be
`P_bar = (float(P)-16384)*(P_max-P_min)/32768 + P_min + P_mode_offset;`

**Comment by spiderkeys** [comment]
@ES-Alexander my guess is that we need to add this mode-based logic to the KellerLD library in Ardupilot as well:
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Baro/AP_Baro_KellerLD.cpp#L253

Seems to be configured for a static 1.0130 bar here as well.

**Comment by ES-Alexander** [comment]
> Seems to be configured for a static 1.0130 bar here as well.

Interesting that that's the wrong number. I wonder if that's intentional given the sensor resolution (at least on our [Bar100](https://bluerobotics.com/store/sensors-sonars-cameras/sensors/bar100-sensor-r2-rp/#tab-technical-details) there's a resolution of 3mbar), or if it's just a mistype and should be 101325Pa instead of 101300Pa.
